### ISSUE TITLE
Readonly classname in use  gives unexpected token

### ISSUE THREAD

**Issue by melvin-ibuildings** [pdepend/pdepend#571] opened 2021-11-09 11:26 UTC
- PHP Depend version: 2.10.1
- PHP Version: 7.4.25
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu 20.04.3 LTS

### Current Behavior
Explain the result that you get.
i get the error
```
The following error occurred:
Unexpected token: ReadOnly, line: 18, col: 33, file: /home/melvin/Projects/publishing-msp-drupal8/modules/rtlbase/src/Factory/JmsSerializerFactory.php.
```

on the code
```
<?php

namespace Drupal\rtlbase\Factory;

use Doctrine\Common\Annotations\AnnotationReader;
use Doctrine\Common\Annotations\AnnotationRegistry;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\AccessorOrder;
use JMS\Serializer\Annotation\AccessType;
use JMS\Serializer\Annotation\Discriminator;
use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation\HandlerCallback;
use JMS\Serializer\Annotation\Inline;
use JMS\Serializer\Annotation\MaxDepth;
use JMS\Serializer\Annotation\ReadOnly;
use JMS\Serializer\Annotation\PostDeserialize;
use JMS\Serializer\Annotation\PostSerialize;
use JMS\Serializer\Annotation\PreSerialize;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Since;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Until;
use JMS\Serializer\Annotation\VirtualProperty;
use JMS\Serializer\Annotation\XmlAttribute;
use JMS\Serializer\Annotation\XmlList;
use JMS\Serializer\Annotation\XmlValue;
use JMS\Serializer\Naming\IdenticalPropertyNamingStrategy;
use JMS\Serializer\Naming\SerializedNameAnnotationStrategy;
use JMS\Serializer\SerializerBuilder;

```

I checked issues and found https://github.com/pdepend/pdepend/issues/566 but running `composer require pdepend/pdepend:dev-master`  did not fix it for my case

### Expected Behavior
Explain the result that you expected.
No errors
### Steps To Reproduce:
ran
`./vendor/bin/pdepend /home/melvin/Projects/publishing-msp-drupal8/modules/rtlbase/src/Factory/JmsSerializerFactory.php`

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment] 2021-11-09 11:27
Please can you check if it happens with `composer require pdepend/pdepend:dev-master`?

**Comment by melvin-ibuildings** [comment] 2021-11-09 11:30
Thanks for the quick reply, but as per the description i did

"I checked issues and found #566 but running composer require pdepend/pdepend:dev-master did not fix it for my case"

I am now on 

```
        {
            "name": "pdepend/pdepend",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/pdepend/pdepend.git",
                "reference": "e614b8c952857f49336cfa592e5d2fd58c936196"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/pdepend/pdepend/zipball/e614b8c952857f49336cfa592e5d2fd58c936196",
                "reference": "e614b8c952857f49336cfa592e5d2fd58c936196",
                "shasum": ""
            },
```

**Comment by kylekatarnls** [comment] 2021-11-09 11:32
OK, thanks. Indeed `e614b8` is the last commit so it's not a duplicate of #566

**Comment by kylekatarnls** [comment] 2021-11-09 11:33
I set the missing PHP version to 8.1.0 (normally `readonly` does not exist as a token before this version) can you confirm you're using PHP 8.1?

**Comment by melvin-ibuildings** [comment] 2021-11-09 11:48
i am using  7.4.25 
```
docker exec -i -t ${PHPHOST} /bin/bash;
bash-5.1# php -v
PHP 7.4.25 (cli) (built: Oct 22 2021 18:26:57) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
```

On as well local, dev machine (docker) and ci environment

**Comment by kylekatarnls** [comment] 2021-11-09 13:54
Hello, I submitted a fix you can try with:
```
composer require pdepend/pdepend:dev-fix/issue-571-readonly-as-part-of-a-class-name
```

**Comment by melvin-ibuildings** [comment] 2021-11-09 14:00
It runs without issues on that branch, thanks

**Closed** 2021-11-10 10:56 UTC
Labels: Bug, php8.1
