### ISSUE TITLE
Terrible performance on Windows if home directory is on network share

### ISSUE THREAD

**Issue by InvisibleSmiley** [pdepend/pdepend#447] opened 2020-01-22 10:24 UTC
- PHP Depend version: 2.6.1
- PHP Version: 7.3.12
- Installation type: Composer
- Operating System / Distribution & Version: Windows 10
- no pdepend.xml / pdepend.xml.dist in directory to be checked with PHPMD

### Current Behavior
Calling PHPMD (2.8.1) with a simple file takes ~6 seconds on Windows if your home directory is on a network share.

### Expected Behavior
The performance should be equal (or very similar) to that if a pdepend.xml / pdepend.xml.dist is present in the directory to be checked with PHPMD (~0.4 seconds).

### Steps To Reproduce:
- have the home directory of your Windows user on a network share (common corporate setup)
- set up current PHPMD (using PHP Depend) for a project
- make sure the project contains no pdepend.xml / pdepend.xml.dist file
- let PHPMD check some file

**Comment by tvbeek** [comment] 2020-01-22 12:42
Thanks for the report, I have one question: do you run PHPMD from your home directory or from your project root?

**Comment by InvisibleSmiley** [comment] 2020-01-22 12:53
> I have one question: do you run PHPMD from your home directory or from your project root?

I run it from the project root which is a subdirectory of my Windows user's home.

**Comment by kylekatarnls** [comment] 2020-01-22 12:58
PDepend user cache lies in HOME as it is for `composer` or many CLI tools. If the access to your HOME directory is slow (which is possibly the root cause and should be handled anyway by your company as an IT issue) you can override it to use a local directory:

```
HOME=C:\phpmd phpmd ...
```

You should compare with some other tools that use the same principle such as: `composer config user.name -g` which is supposed to read `~/.composer` directory. If it is either slow, then you're more likely have a bandwidth issue not related to PDepend/PHPMD.

**Comment by InvisibleSmiley** [comment] 2020-01-22 13:11
> PDepend user cache lies in HOME as it is for `composer` or many CLI tools. If the access to your HOME directory is slow (which is possibly the root cause and should be handled anyway by your company as an IT issue) you can override it to use a local directory:
> 
> ```
> HOME=C:\phpmd phpmd ...
> ```

I set the HOME environment variable to my Windows user profile directory (say C:\Users\foo) long ago, ever since I found that this accelerates starting commands like vim from Git Bash.

**Comment by kylekatarnls** [comment] 2020-01-22 13:19
Found it:
```php
        if ((PHP_OS === 'Darwin') || (PHP_OS === 'CYGWIN') || (false === stripos(PHP_OS, 'win'))) {
            return getenv('HOME');
        }
        return getenv('HOMEDRIVE') . getenv('HOMEPATH');
```
This is how PDepend find the home path. I guess we should first get `getenv('HOME')` for Windows too and only fallback to HOMEDRIVE + HOMEPATH if it's empty.

**Comment by InvisibleSmiley** [comment] 2020-01-22 13:22
> 
> 
> Found it:
> 
> ```
>         if ((PHP_OS === 'Darwin') || (PHP_OS === 'CYGWIN') || (false === stripos(PHP_OS, 'win'))) {
>             return getenv('HOME');
>         }
>         return getenv('HOMEDRIVE') . getenv('HOMEPATH');
> ```
> 
> This is how PDepend find the home path. I guess we should first get `getenv('HOME')` for Windows too and only fallback to HOMEDRIVE + HOMEPATH if it's empty.

Makes sense, sounds good to me! :)

**Comment by kylekatarnls** [comment] 2020-04-04 13:50
On the next version or yet in dev-master you can now set custom directory to HOME for any OS.

**Comment by ravage84** [comment] 2020-04-09 13:53
@InvisibleSmiley I am going to close this issue as the related PR has been merged.

We identified a general issue with the file caching mechanism of PDepend, which we will track in another issue.

Please try to make use of the now available ``HOME`` environment variable to work around your specific problem.
In general I would try to stay away from working on a network share as often as I can.

**Closed by ravage84** 2020-04-09 13:53 UTC
Labels: CLI, Good first issue, Windows
