### ISSUE TITLE
PHP 7.1  - Unexpected token: |

### ISSUE THREAD

**Issue by careys7** [pdepend/pdepend#318] opened 2017-09-27 00:09 UTC
Using catch block with multiple exception classes separated by the pipe character: 

http://php.net/manual/en/language.exceptions.php#language.exceptions.catch

> In PHP 7.1 and later, a catch block may specify multiple exceptions using the pipe (|) character. This is useful for when different exceptions from different class hierarchies are handled the same.

**Comment by chrisminett** [comment] 2017-10-03 14:38
#298 duplicate

**Comment by emirb** [comment] 2017-11-10 00:54
Closing as it is a duplicate of #298.

**Closed by emirb** 2017-11-10 00:54 UTC
Labels: PHP71
