### ISSUE TITLE
php 5.6 constant syntax not supported

### ISSUE THREAD

**Issue by tystr** [pdepend/pdepend#209] opened 2015-05-27 02:26 UTC
I have a constant defined like this:
```PHP
    const MONTHS = [
        'January'   => 'January',
        'February'  => 'February',
        // ...
    ];
```
pdepend errors with the following message:
`Unexpected token: =>`

In another file I have a constant defined like this:
```PHP
    const SCALAR_TYPES = ['string', 'int', 'float', 'boolean'];
```
pdepend errors with the following message:
`Unexpected token: 'int'`

**Comment by internalsystemerror** [comment] 2015-09-10 04:55
Duplicate of https://github.com/pdepend/pdepend/issues/192

**Comment by manuelpichler** [comment] 2015-09-20 18:43
Duplicate with #192

**Closed by manuelpichler** 2015-09-20 18:43 UTC
