### ISSUE TITLE
PDepend stops with exception: UnexpectedTokenException

### ISSUE THREAD

**Issue by frankdekker** [pdepend/pdepend#570] opened 2021-11-01 17:52 UTC
- PHP Depend version: 2.10.1
- PHP Version: PHP 8.0.10
- Installation type: composer
- Operating System / Distribution & Version: Debian 10

### Current Behavior
Crashes with exception when invoked from PHPMD:
```
<pmd version="@package_version@" tool="phpmd" timestamp="2021-11-01T18:36:05+01:00">
  <error filename="" msg="Unexpected token: readOnly, line: 64, col: 23, file: /dev/src/Lib/System/Azure/AzureAccess.php.
#0 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7460): PDepend\Source\Parser\UnexpectedTokenException-&gt;__construct()
#1 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7426): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;getUnexpectedTokenException()
#2 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4886): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;consumeToken()
#3 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4965): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseVariable()
#4 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4236): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseCompoundVariableOrVariableVariableOrVariable()
#5 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4580): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseMemberPrimaryPrefix()
#6 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4535): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseVariableOrFunctionPostfixOrMemberPrimaryPrefix()
#7 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2801): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseVariableOrConstantOrPrimaryPrefix()
#8 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3862): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseOptionalExpression()
#9 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3880): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;buildReturnStatement()
#10 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6131): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseReturnStatement()
#11 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6068): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseOptionalStatement()
#12 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1282): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseScope()
#13 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1234): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseCallableDeclaration()
#14 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(991): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseMethodDeclaration()
#15 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(89): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseMethodOrFieldDeclaration()
#16 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74-&gt;parseMethodOrFieldDeclaration()
#17 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseTypeBody()
#18 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6199): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseClassDeclaration()
#19 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parseOptionalStatement()
#20 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser-&gt;parse()
#21 /dev/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine-&gt;performParseProcess()
#22 /dev/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine-&gt;analyze()
#23 /dev/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(240): PHPMD\Parser-&gt;parse()
#24 /dev/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(136): PHPMD\PHPMD-&gt;processFiles()
#25 /dev/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(184): PHPMD\TextUI\Command-&gt;run()
#26 /dev/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
```

Crashes on:
```php
    /**
     * @return bool
     */
    public function isReadOnly()
    {
        return $this->readOnly;
    }
```

### Expected Behavior
Similar behaviour to 2.10.0. Let's not throw exceptions :)

### Steps To Reproduce:
Create class with the above getter method.
Use PHPMD to inspect this file with pdepend 2.10.1
Observe crash.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment] 2021-11-01 21:18
Hello, this is a duplicate of #566 which will be fixed in the next version, the fix is already merged, so you can `composer require pdepend/pdepend:dev-master` to test it.

Thanks.

**Closed by kylekatarnls** 2021-11-01 21:18 UTC
